### ISSUE TITLE
Getting Demo to work

### ISSUE THREAD

**Issue by msj121** [andreasplesch/aframe-heightgrid-component#1]
Hi,
  I tried running the demo code on the main page at codepen.io, but there are too many issues: **http://codepen.io/msj121/pen/XKrVQq**

I tried using a simple .html file on my desktop with one error:
core:schema:warn Unknown component property: height +0ms

In either cases nothing shows up, but at least with the simple html file, the 3d glasses are in the corner, but no height map.

**Comment by andreasplesch** [comment]
Please read README.md and study the basic example.

**Comment by msj121** [comment]
Just out of curiosity if I download the zip and click basic/advanced am I supposed to see something? Basic I just see a monkey's face as an image... This is using an updated chrome

**Comment by andreasplesch** [comment]
The basic example shows a couple simple (2x2, 4x3) textured grids.

http://andreasplesch.github.io/aframe-heightgrid-component/basic/index.html

You will need to serve the files rather than just open them in a browser.
